services:
#  serviceA:
#    image: openjdk:17
#    volumes:
#      - ./serviceA/build/libs/:/app
#    command: bash -c "cd /app && java -jar serviceA-0.0.1-SNAPSHOT.jar"
#    ports:
#      - 8080:8080
#  serviceB:
#    image: openjdk:17
#    volumes:
#      - ./serviceB/build/libs/:/app
#    command: bash -c "cd /app && java -jar serviceB-0.0.1-SNAPSHOT.jar"
#    ports:
#      - 8081:8081
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./scripts/users.js:/docker-entrypoint-initdb.d/001_users.js:ro
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: demo
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_USERNAME: admin

volumes:
  mongodb:
  mongodb_config: